spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciadorFinanceiro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    br.projetos.gerenciadorFinanceiro: TRACE

cors:
  originPatterns: http://localhost:8080,http://localhost:3000

file:
  upload-dir: /Users/bruno/Downloads