CREATE TABLE IF NOT EXISTS public.categoria
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta numeric(10,2),
    status character varying(10),
    nome character varying(20) NOT NULL,
    tipo character varying(31) NOT NULL
)