CREATE TABLE IF NOT EXISTS public.lancamento
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor numeric(10,2) NOT NULL,
    cartao_id bigint,
    categoria_id bigint,
    descricao character varying(100) NOT NULL,
    data character varying(255) NOT NULL,
    
    CONSTRAINT FK_lancamento_cartao FOREIGN KEY (cartao_id)
        REFERENCES public.cartao (id),
        
    CONSTRAINT FK_lancamento_categoria FOREIGN KEY (categoria_id)
        REFERENCES public.categoria (id)
)